### ISSUE TITLE
Your project as a reference in react-native-sensors

### ISSUE THREAD

**Issue by DanielMSchmidt** [Matzielab/imagination-react-native#1]
Hey there,

I like the way you use `react-native-sensors` and I would like to link this project in the readme, would this be okay for you?

**Comment by Matzielab** [comment]
Hi Daniel,

Thanks! I've updated the project to be more informative. Go for it, i feel honored to be linked. It's a great lib!

**Comment by DanielMSchmidt** [comment]
Cool, great to hear 👍
